name: run-discord-bot

on:
  # test
  # push:
  #  branches:
  #   - main
  schedule:
    - cron: '35 8 * * 1-5' # weekdays 17:35

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.2' # install the python version needed
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install pytz
          python3 -m pip install -U discord.py
          python3 -m pip install -U html5lib
      - name: Test env vars
        run: python -c 'import os;print(os.environ)'
        env:
          discord_token: ${{ secrets.DISCORD_TOKEN }}
      - name: Execute py script
        env:
          discord_token: ${{ secrets.DISCORD_TOKEN }}
        run: python3 discord_bot.py
