name: run-discord-bot

on:
  schedule:
    - cron: '*/5 * * * *' # runs every five minutes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.2' # install the python version needed
      - name: install packages
        run: |
          pip3 install -r requirements.txt
          python3 -m pip install -U discord.py
      - name: execute py script
        env:
          discord_token: ${{ secrets.DISCORD_TOKEN }}
        run: python3 discord_bot.py